server:
  port: 8088

jasypt:
  encryptor:
    password: test

spring:
  datasource:
    url: jdbc:mysql://120.79.101.115:3306/tdsnzgc?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: ENC(8123qbu/kz5xnq1w3To3fQ==)
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #初始大小
    initialSize: 5
    #最小
    minIdle: 5
    #最大
    maxActive: 20
    #获取连接等待超时时间
    maxWait: 60000

  redis:
    database: 0
    host: 120.79.101.115
    port: 6379
    password:
    pool:
      maxActive: 200
      maxWait: -1
      maxIdle: 0
    timeout: 1000

mybatis:
  typeAliasesPackage: com.tdsnzgc.manage_web.pojo
  mapperLocations: classpath:/mapper/**/*.xml
  configuration:
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params=count: countSql

tokenKey: 235678
tokenExpires: 86400 #token 失效时间
