SERVICE_HOST: ENC(Gj4tIFU5xhKGTLg9q7SCGF+2JVGZNeD9)
server:
  port: 8088

jasypt:
  encryptor:
    password: bnnpyudnae1
spring:
  datasource:
    url: jdbc:mysql://${SERVICE_HOST}:3306/tdsnzgc?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: ENC(RDbntdTqDkZ0WG6Xf+7DKg==)
    password: ENC(KjYg8Q366CI9y4y4jX47lw==)
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    #初始大小
    initialSize: 5
    #最小
    minIdle: 5
    #最大
    maxActive: 20
    #获取连接等待超时时间
    maxWait: 60000

  redis:
    database: 0
    host: ${SERVICE_HOST}
    port: 6379
    password:
    pool:
      maxActive: 200
      maxWait: -1
      maxIdle: 0
    timeout: 1000

mybatis:
  typeAliasesPackage: com.tdsnzgc.manage_web.pojo
  mapperLocations: classpath:/mapper/**/*.xml
  configuration:
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params=count: countSql

tokenKey: 235678
tokenExpires: 86400 #token 失效时间
